/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SparqlRouteImport } from './routes/sparql'
import { Route as CorpusIdIndexRouteImport } from './routes/$corpusId/index'
import { Route as CorpusIdPlayIdRouteRouteImport } from './routes/$corpusId/$playId/route'
import { Route as DocSlugRouteImport } from './routes/doc/$slug'
import { Route as DocApiRouteImport } from './routes/doc/api'
import { Route as DocCorporaRouteImport } from './routes/doc/corpora'
import { Route as DocOddRouteImport } from './routes/doc/odd'
import { Route as CorpusIdPlayIdIndexRouteImport } from './routes/$corpusId/$playId/index'
import { Route as CorpusIdPlayIdTabRouteImport } from './routes/$corpusId/$playId/$tab'
import { Route as DocLegacyApiRouteImport } from './routes/doc/legacy.api'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SparqlRoute = SparqlRouteImport.update({
  id: '/sparql',
  path: '/sparql',
  getParentRoute: () => rootRouteImport,
} as any)
const CorpusIdIndexRoute = CorpusIdIndexRouteImport.update({
  id: '/$corpusId/',
  path: '/$corpusId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorpusIdPlayIdRouteRoute = CorpusIdPlayIdRouteRouteImport.update({
  id: '/$corpusId/$playId',
  path: '/$corpusId/$playId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocSlugRoute = DocSlugRouteImport.update({
  id: '/doc/$slug',
  path: '/doc/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocApiRoute = DocApiRouteImport.update({
  id: '/doc/api',
  path: '/doc/api',
  getParentRoute: () => rootRouteImport,
} as any)
const DocCorporaRoute = DocCorporaRouteImport.update({
  id: '/doc/corpora',
  path: '/doc/corpora',
  getParentRoute: () => rootRouteImport,
} as any)
const DocOddRoute = DocOddRouteImport.update({
  id: '/doc/odd',
  path: '/doc/odd',
  getParentRoute: () => rootRouteImport,
} as any)
const CorpusIdPlayIdIndexRoute = CorpusIdPlayIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CorpusIdPlayIdRouteRoute,
} as any)
const CorpusIdPlayIdTabRoute = CorpusIdPlayIdTabRouteImport.update({
  id: '/$tab',
  path: '/$tab',
  getParentRoute: () => CorpusIdPlayIdRouteRoute,
} as any)
const DocLegacyApiRoute = DocLegacyApiRouteImport.update({
  id: '/doc/legacy/api',
  path: '/doc/legacy/api',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sparql': typeof SparqlRoute
  '/$corpusId/$playId': typeof CorpusIdPlayIdRouteRouteWithChildren
  '/doc/$slug': typeof DocSlugRoute
  '/doc/api': typeof DocApiRoute
  '/doc/corpora': typeof DocCorporaRoute
  '/doc/odd': typeof DocOddRoute
  '/$corpusId/': typeof CorpusIdIndexRoute
  '/$corpusId/$playId/$tab': typeof CorpusIdPlayIdTabRoute
  '/doc/legacy/api': typeof DocLegacyApiRoute
  '/$corpusId/$playId/': typeof CorpusIdPlayIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sparql': typeof SparqlRoute
  '/doc/$slug': typeof DocSlugRoute
  '/doc/api': typeof DocApiRoute
  '/doc/corpora': typeof DocCorporaRoute
  '/doc/odd': typeof DocOddRoute
  '/$corpusId': typeof CorpusIdIndexRoute
  '/$corpusId/$playId/$tab': typeof CorpusIdPlayIdTabRoute
  '/doc/legacy/api': typeof DocLegacyApiRoute
  '/$corpusId/$playId': typeof CorpusIdPlayIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sparql': typeof SparqlRoute
  '/$corpusId/$playId': typeof CorpusIdPlayIdRouteRouteWithChildren
  '/doc/$slug': typeof DocSlugRoute
  '/doc/api': typeof DocApiRoute
  '/doc/corpora': typeof DocCorporaRoute
  '/doc/odd': typeof DocOddRoute
  '/$corpusId/': typeof CorpusIdIndexRoute
  '/$corpusId/$playId/$tab': typeof CorpusIdPlayIdTabRoute
  '/doc/legacy/api': typeof DocLegacyApiRoute
  '/$corpusId/$playId/': typeof CorpusIdPlayIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sparql'
    | '/$corpusId/$playId'
    | '/doc/$slug'
    | '/doc/api'
    | '/doc/corpora'
    | '/doc/odd'
    | '/$corpusId/'
    | '/$corpusId/$playId/$tab'
    | '/doc/legacy/api'
    | '/$corpusId/$playId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sparql'
    | '/doc/$slug'
    | '/doc/api'
    | '/doc/corpora'
    | '/doc/odd'
    | '/$corpusId'
    | '/$corpusId/$playId/$tab'
    | '/doc/legacy/api'
    | '/$corpusId/$playId'
  id:
    | '__root__'
    | '/'
    | '/sparql'
    | '/$corpusId/$playId'
    | '/doc/$slug'
    | '/doc/api'
    | '/doc/corpora'
    | '/doc/odd'
    | '/$corpusId/'
    | '/$corpusId/$playId/$tab'
    | '/doc/legacy/api'
    | '/$corpusId/$playId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SparqlRoute: typeof SparqlRoute
  CorpusIdPlayIdRouteRoute: typeof CorpusIdPlayIdRouteRouteWithChildren
  DocSlugRoute: typeof DocSlugRoute
  DocApiRoute: typeof DocApiRoute
  DocCorporaRoute: typeof DocCorporaRoute
  DocOddRoute: typeof DocOddRoute
  CorpusIdIndexRoute: typeof CorpusIdIndexRoute
  DocLegacyApiRoute: typeof DocLegacyApiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sparql': {
      id: '/sparql'
      path: '/sparql'
      fullPath: '/sparql'
      preLoaderRoute: typeof SparqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$corpusId/': {
      id: '/$corpusId/'
      path: '/$corpusId'
      fullPath: '/$corpusId/'
      preLoaderRoute: typeof CorpusIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$corpusId/$playId': {
      id: '/$corpusId/$playId'
      path: '/$corpusId/$playId'
      fullPath: '/$corpusId/$playId'
      preLoaderRoute: typeof CorpusIdPlayIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/$slug': {
      id: '/doc/$slug'
      path: '/doc/$slug'
      fullPath: '/doc/$slug'
      preLoaderRoute: typeof DocSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/api': {
      id: '/doc/api'
      path: '/doc/api'
      fullPath: '/doc/api'
      preLoaderRoute: typeof DocApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/corpora': {
      id: '/doc/corpora'
      path: '/doc/corpora'
      fullPath: '/doc/corpora'
      preLoaderRoute: typeof DocCorporaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc/odd': {
      id: '/doc/odd'
      path: '/doc/odd'
      fullPath: '/doc/odd'
      preLoaderRoute: typeof DocOddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$corpusId/$playId/': {
      id: '/$corpusId/$playId/'
      path: '/'
      fullPath: '/$corpusId/$playId/'
      preLoaderRoute: typeof CorpusIdPlayIdIndexRouteImport
      parentRoute: typeof CorpusIdPlayIdRouteRoute
    }
    '/$corpusId/$playId/$tab': {
      id: '/$corpusId/$playId/$tab'
      path: '/$tab'
      fullPath: '/$corpusId/$playId/$tab'
      preLoaderRoute: typeof CorpusIdPlayIdTabRouteImport
      parentRoute: typeof CorpusIdPlayIdRouteRoute
    }
    '/doc/legacy/api': {
      id: '/doc/legacy/api'
      path: '/doc/legacy/api'
      fullPath: '/doc/legacy/api'
      preLoaderRoute: typeof DocLegacyApiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CorpusIdPlayIdRouteRouteChildren {
  CorpusIdPlayIdTabRoute: typeof CorpusIdPlayIdTabRoute
  CorpusIdPlayIdIndexRoute: typeof CorpusIdPlayIdIndexRoute
}

const CorpusIdPlayIdRouteRouteChildren: CorpusIdPlayIdRouteRouteChildren = {
  CorpusIdPlayIdTabRoute: CorpusIdPlayIdTabRoute,
  CorpusIdPlayIdIndexRoute: CorpusIdPlayIdIndexRoute,
}

const CorpusIdPlayIdRouteRouteWithChildren =
  CorpusIdPlayIdRouteRoute._addFileChildren(CorpusIdPlayIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SparqlRoute: SparqlRoute,
  CorpusIdPlayIdRouteRoute: CorpusIdPlayIdRouteRouteWithChildren,
  DocSlugRoute: DocSlugRoute,
  DocApiRoute: DocApiRoute,
  DocCorporaRoute: DocCorporaRoute,
  DocOddRoute: DocOddRoute,
  CorpusIdIndexRoute: CorpusIdIndexRoute,
  DocLegacyApiRoute: DocLegacyApiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
