name: Deploy to production

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  production:
    uses: dracor-org/dracor-frontend/.github/workflows/deployment.yml@main
    with:
      host: dracor.org
      deploy-path: /var/www/html
    secrets:
      deploy-key: ${{ secrets.DRACOR_ORG_DEPLOY_KEY }}
      deploy-user: ${{ secrets.DRACOR_ORG_DEPLOY_USER }}
