name: Deploy to staging

on:
  workflow_dispatch:
  release:
  push:
    branches: [main]

jobs:
  staging:
    uses: dracor-org/dracor-frontend/.github/workflows/deployment.yml@main
    with:
      host: staging.dracor.org
      deploy-path: /var/www/html
    secrets:
      deploy-key: ${{ secrets.DRACOR_ORG_DEPLOY_KEY }}
      deploy-user: ${{ secrets.DRACOR_ORG_DEPLOY_USER }}
